//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4 E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g 2014-04-15 21:18:52

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4")]
[System.CLSCompliant(false)]
public partial class NPortugolLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int T__39=39;
	public const int T__40=40;
	public const int T__41=41;
	public const int T__42=42;
	public const int T__43=43;
	public const int T__44=44;
	public const int T__45=45;
	public const int T__46=46;
	public const int T__47=47;
	public const int T__48=48;
	public const int T__49=49;
	public const int T__50=50;
	public const int T__51=51;
	public const int T__52=52;
	public const int T__53=53;
	public const int T__54=54;
	public const int T__55=55;
	public const int T__56=56;
	public const int T__57=57;
	public const int T__58=58;
	public const int T__59=59;
	public const int T__60=60;
	public const int T__61=61;
	public const int T__62=62;
	public const int T__63=63;
	public const int T__64=64;
	public const int T__65=65;
	public const int T__66=66;
	public const int T__67=67;
	public const int T__68=68;
	public const int T__69=69;
	public const int T__70=70;
	public const int T__71=71;
	public const int T__72=72;
	public const int T__73=73;
	public const int T__74=74;
	public const int T__75=75;
	public const int AR=4;
	public const int ARG=5;
	public const int ASGN=6;
	public const int ASM=7;
	public const int CALL=8;
	public const int CHAR=9;
	public const int DEC=10;
	public const int ESC_SEQ=11;
	public const int EXP=12;
	public const int EXPONENT=13;
	public const int F=14;
	public const int FLOAT=15;
	public const int FUNC=16;
	public const int HEX_DIGIT=17;
	public const int ID=18;
	public const int ILIST=19;
	public const int INDEX=20;
	public const int INIT=21;
	public const int INT=22;
	public const int JMP=23;
	public const int LEXP=24;
	public const int LOOP=25;
	public const int MCALL=26;
	public const int NEWLINE=27;
	public const int OCTAL_ESC=28;
	public const int PARAM=29;
	public const int PCALL=30;
	public const int RET=31;
	public const int SJMP=32;
	public const int SLIST=33;
	public const int STRING=34;
	public const int T=35;
	public const int UNICODE_ESC=36;
	public const int VAR=37;
	public const int WS=38;

    // delegates
    // delegators

	public NPortugolLexer()
	{
		OnCreated();
	}

	public NPortugolLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public NPortugolLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_T__39();
	partial void LeaveRule_T__39();

	// $ANTLR start "T__39"
	[GrammarRule("T__39")]
	private void mT__39()
	{
		EnterRule_T__39();
		EnterRule("T__39", 1);
		TraceIn("T__39", 1);
		try
		{
			int _type = T__39;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:7:7: ( '!=' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:7:9: '!='
			{
			DebugLocation(7, 9);
			Match("!="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__39", 1);
			LeaveRule("T__39", 1);
			LeaveRule_T__39();
		}
	}
	// $ANTLR end "T__39"

	partial void EnterRule_T__40();
	partial void LeaveRule_T__40();

	// $ANTLR start "T__40"
	[GrammarRule("T__40")]
	private void mT__40()
	{
		EnterRule_T__40();
		EnterRule("T__40", 2);
		TraceIn("T__40", 2);
		try
		{
			int _type = T__40;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:8:7: ( '#' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:8:9: '#'
			{
			DebugLocation(8, 9);
			Match('#'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__40", 2);
			LeaveRule("T__40", 2);
			LeaveRule_T__40();
		}
	}
	// $ANTLR end "T__40"

	partial void EnterRule_T__41();
	partial void LeaveRule_T__41();

	// $ANTLR start "T__41"
	[GrammarRule("T__41")]
	private void mT__41()
	{
		EnterRule_T__41();
		EnterRule("T__41", 3);
		TraceIn("T__41", 3);
		try
		{
			int _type = T__41;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:9:7: ( '%' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:9:9: '%'
			{
			DebugLocation(9, 9);
			Match('%'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__41", 3);
			LeaveRule("T__41", 3);
			LeaveRule_T__41();
		}
	}
	// $ANTLR end "T__41"

	partial void EnterRule_T__42();
	partial void LeaveRule_T__42();

	// $ANTLR start "T__42"
	[GrammarRule("T__42")]
	private void mT__42()
	{
		EnterRule_T__42();
		EnterRule("T__42", 4);
		TraceIn("T__42", 4);
		try
		{
			int _type = T__42;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:10:7: ( '(' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:10:9: '('
			{
			DebugLocation(10, 9);
			Match('('); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__42", 4);
			LeaveRule("T__42", 4);
			LeaveRule_T__42();
		}
	}
	// $ANTLR end "T__42"

	partial void EnterRule_T__43();
	partial void LeaveRule_T__43();

	// $ANTLR start "T__43"
	[GrammarRule("T__43")]
	private void mT__43()
	{
		EnterRule_T__43();
		EnterRule("T__43", 5);
		TraceIn("T__43", 5);
		try
		{
			int _type = T__43;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:11:7: ( ')' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:11:9: ')'
			{
			DebugLocation(11, 9);
			Match(')'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__43", 5);
			LeaveRule("T__43", 5);
			LeaveRule_T__43();
		}
	}
	// $ANTLR end "T__43"

	partial void EnterRule_T__44();
	partial void LeaveRule_T__44();

	// $ANTLR start "T__44"
	[GrammarRule("T__44")]
	private void mT__44()
	{
		EnterRule_T__44();
		EnterRule("T__44", 6);
		TraceIn("T__44", 6);
		try
		{
			int _type = T__44;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:12:7: ( '*' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:12:9: '*'
			{
			DebugLocation(12, 9);
			Match('*'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__44", 6);
			LeaveRule("T__44", 6);
			LeaveRule_T__44();
		}
	}
	// $ANTLR end "T__44"

	partial void EnterRule_T__45();
	partial void LeaveRule_T__45();

	// $ANTLR start "T__45"
	[GrammarRule("T__45")]
	private void mT__45()
	{
		EnterRule_T__45();
		EnterRule("T__45", 7);
		TraceIn("T__45", 7);
		try
		{
			int _type = T__45;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:13:7: ( '+' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:13:9: '+'
			{
			DebugLocation(13, 9);
			Match('+'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__45", 7);
			LeaveRule("T__45", 7);
			LeaveRule_T__45();
		}
	}
	// $ANTLR end "T__45"

	partial void EnterRule_T__46();
	partial void LeaveRule_T__46();

	// $ANTLR start "T__46"
	[GrammarRule("T__46")]
	private void mT__46()
	{
		EnterRule_T__46();
		EnterRule("T__46", 8);
		TraceIn("T__46", 8);
		try
		{
			int _type = T__46;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:14:7: ( ',' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:14:9: ','
			{
			DebugLocation(14, 9);
			Match(','); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__46", 8);
			LeaveRule("T__46", 8);
			LeaveRule_T__46();
		}
	}
	// $ANTLR end "T__46"

	partial void EnterRule_T__47();
	partial void LeaveRule_T__47();

	// $ANTLR start "T__47"
	[GrammarRule("T__47")]
	private void mT__47()
	{
		EnterRule_T__47();
		EnterRule("T__47", 9);
		TraceIn("T__47", 9);
		try
		{
			int _type = T__47;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:15:7: ( '-' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:15:9: '-'
			{
			DebugLocation(15, 9);
			Match('-'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__47", 9);
			LeaveRule("T__47", 9);
			LeaveRule_T__47();
		}
	}
	// $ANTLR end "T__47"

	partial void EnterRule_T__48();
	partial void LeaveRule_T__48();

	// $ANTLR start "T__48"
	[GrammarRule("T__48")]
	private void mT__48()
	{
		EnterRule_T__48();
		EnterRule("T__48", 10);
		TraceIn("T__48", 10);
		try
		{
			int _type = T__48;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:16:7: ( '.' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:16:9: '.'
			{
			DebugLocation(16, 9);
			Match('.'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__48", 10);
			LeaveRule("T__48", 10);
			LeaveRule_T__48();
		}
	}
	// $ANTLR end "T__48"

	partial void EnterRule_T__49();
	partial void LeaveRule_T__49();

	// $ANTLR start "T__49"
	[GrammarRule("T__49")]
	private void mT__49()
	{
		EnterRule_T__49();
		EnterRule("T__49", 11);
		TraceIn("T__49", 11);
		try
		{
			int _type = T__49;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:17:7: ( '..' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:17:9: '..'
			{
			DebugLocation(17, 9);
			Match(".."); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__49", 11);
			LeaveRule("T__49", 11);
			LeaveRule_T__49();
		}
	}
	// $ANTLR end "T__49"

	partial void EnterRule_T__50();
	partial void LeaveRule_T__50();

	// $ANTLR start "T__50"
	[GrammarRule("T__50")]
	private void mT__50()
	{
		EnterRule_T__50();
		EnterRule("T__50", 12);
		TraceIn("T__50", 12);
		try
		{
			int _type = T__50;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:18:7: ( '/' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:18:9: '/'
			{
			DebugLocation(18, 9);
			Match('/'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__50", 12);
			LeaveRule("T__50", 12);
			LeaveRule_T__50();
		}
	}
	// $ANTLR end "T__50"

	partial void EnterRule_T__51();
	partial void LeaveRule_T__51();

	// $ANTLR start "T__51"
	[GrammarRule("T__51")]
	private void mT__51()
	{
		EnterRule_T__51();
		EnterRule("T__51", 13);
		TraceIn("T__51", 13);
		try
		{
			int _type = T__51;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:19:7: ( ';' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:19:9: ';'
			{
			DebugLocation(19, 9);
			Match(';'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__51", 13);
			LeaveRule("T__51", 13);
			LeaveRule_T__51();
		}
	}
	// $ANTLR end "T__51"

	partial void EnterRule_T__52();
	partial void LeaveRule_T__52();

	// $ANTLR start "T__52"
	[GrammarRule("T__52")]
	private void mT__52()
	{
		EnterRule_T__52();
		EnterRule("T__52", 14);
		TraceIn("T__52", 14);
		try
		{
			int _type = T__52;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:20:7: ( '<' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:20:9: '<'
			{
			DebugLocation(20, 9);
			Match('<'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__52", 14);
			LeaveRule("T__52", 14);
			LeaveRule_T__52();
		}
	}
	// $ANTLR end "T__52"

	partial void EnterRule_T__53();
	partial void LeaveRule_T__53();

	// $ANTLR start "T__53"
	[GrammarRule("T__53")]
	private void mT__53()
	{
		EnterRule_T__53();
		EnterRule("T__53", 15);
		TraceIn("T__53", 15);
		try
		{
			int _type = T__53;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:21:7: ( '<=' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:21:9: '<='
			{
			DebugLocation(21, 9);
			Match("<="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__53", 15);
			LeaveRule("T__53", 15);
			LeaveRule_T__53();
		}
	}
	// $ANTLR end "T__53"

	partial void EnterRule_T__54();
	partial void LeaveRule_T__54();

	// $ANTLR start "T__54"
	[GrammarRule("T__54")]
	private void mT__54()
	{
		EnterRule_T__54();
		EnterRule("T__54", 16);
		TraceIn("T__54", 16);
		try
		{
			int _type = T__54;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:22:7: ( '=' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:22:9: '='
			{
			DebugLocation(22, 9);
			Match('='); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__54", 16);
			LeaveRule("T__54", 16);
			LeaveRule_T__54();
		}
	}
	// $ANTLR end "T__54"

	partial void EnterRule_T__55();
	partial void LeaveRule_T__55();

	// $ANTLR start "T__55"
	[GrammarRule("T__55")]
	private void mT__55()
	{
		EnterRule_T__55();
		EnterRule("T__55", 17);
		TraceIn("T__55", 17);
		try
		{
			int _type = T__55;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:23:7: ( '==' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:23:9: '=='
			{
			DebugLocation(23, 9);
			Match("=="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__55", 17);
			LeaveRule("T__55", 17);
			LeaveRule_T__55();
		}
	}
	// $ANTLR end "T__55"

	partial void EnterRule_T__56();
	partial void LeaveRule_T__56();

	// $ANTLR start "T__56"
	[GrammarRule("T__56")]
	private void mT__56()
	{
		EnterRule_T__56();
		EnterRule("T__56", 18);
		TraceIn("T__56", 18);
		try
		{
			int _type = T__56;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:24:7: ( '>' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:24:9: '>'
			{
			DebugLocation(24, 9);
			Match('>'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__56", 18);
			LeaveRule("T__56", 18);
			LeaveRule_T__56();
		}
	}
	// $ANTLR end "T__56"

	partial void EnterRule_T__57();
	partial void LeaveRule_T__57();

	// $ANTLR start "T__57"
	[GrammarRule("T__57")]
	private void mT__57()
	{
		EnterRule_T__57();
		EnterRule("T__57", 19);
		TraceIn("T__57", 19);
		try
		{
			int _type = T__57;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:25:7: ( '>=' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:25:9: '>='
			{
			DebugLocation(25, 9);
			Match(">="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__57", 19);
			LeaveRule("T__57", 19);
			LeaveRule_T__57();
		}
	}
	// $ANTLR end "T__57"

	partial void EnterRule_T__58();
	partial void LeaveRule_T__58();

	// $ANTLR start "T__58"
	[GrammarRule("T__58")]
	private void mT__58()
	{
		EnterRule_T__58();
		EnterRule("T__58", 20);
		TraceIn("T__58", 20);
		try
		{
			int _type = T__58;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:26:7: ( '[' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:26:9: '['
			{
			DebugLocation(26, 9);
			Match('['); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__58", 20);
			LeaveRule("T__58", 20);
			LeaveRule_T__58();
		}
	}
	// $ANTLR end "T__58"

	partial void EnterRule_T__59();
	partial void LeaveRule_T__59();

	// $ANTLR start "T__59"
	[GrammarRule("T__59")]
	private void mT__59()
	{
		EnterRule_T__59();
		EnterRule("T__59", 21);
		TraceIn("T__59", 21);
		try
		{
			int _type = T__59;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:27:7: ( ']' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:27:9: ']'
			{
			DebugLocation(27, 9);
			Match(']'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__59", 21);
			LeaveRule("T__59", 21);
			LeaveRule_T__59();
		}
	}
	// $ANTLR end "T__59"

	partial void EnterRule_T__60();
	partial void LeaveRule_T__60();

	// $ANTLR start "T__60"
	[GrammarRule("T__60")]
	private void mT__60()
	{
		EnterRule_T__60();
		EnterRule("T__60", 22);
		TraceIn("T__60", 22);
		try
		{
			int _type = T__60;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:28:7: ( 'até' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:28:9: 'até'
			{
			DebugLocation(28, 9);
			Match("até"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__60", 22);
			LeaveRule("T__60", 22);
			LeaveRule_T__60();
		}
	}
	// $ANTLR end "T__60"

	partial void EnterRule_T__61();
	partial void LeaveRule_T__61();

	// $ANTLR start "T__61"
	[GrammarRule("T__61")]
	private void mT__61()
	{
		EnterRule_T__61();
		EnterRule("T__61", 23);
		TraceIn("T__61", 23);
		try
		{
			int _type = T__61;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:29:7: ( 'decrescente' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:29:9: 'decrescente'
			{
			DebugLocation(29, 9);
			Match("decrescente"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__61", 23);
			LeaveRule("T__61", 23);
			LeaveRule_T__61();
		}
	}
	// $ANTLR end "T__61"

	partial void EnterRule_T__62();
	partial void LeaveRule_T__62();

	// $ANTLR start "T__62"
	[GrammarRule("T__62")]
	private void mT__62()
	{
		EnterRule_T__62();
		EnterRule("T__62", 24);
		TraceIn("T__62", 24);
		try
		{
			int _type = T__62;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:30:7: ( 'e' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:30:9: 'e'
			{
			DebugLocation(30, 9);
			Match('e'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__62", 24);
			LeaveRule("T__62", 24);
			LeaveRule_T__62();
		}
	}
	// $ANTLR end "T__62"

	partial void EnterRule_T__63();
	partial void LeaveRule_T__63();

	// $ANTLR start "T__63"
	[GrammarRule("T__63")]
	private void mT__63()
	{
		EnterRule_T__63();
		EnterRule("T__63", 25);
		TraceIn("T__63", 25);
		try
		{
			int _type = T__63;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:31:7: ( 'enquanto' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:31:9: 'enquanto'
			{
			DebugLocation(31, 9);
			Match("enquanto"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__63", 25);
			LeaveRule("T__63", 25);
			LeaveRule_T__63();
		}
	}
	// $ANTLR end "T__63"

	partial void EnterRule_T__64();
	partial void LeaveRule_T__64();

	// $ANTLR start "T__64"
	[GrammarRule("T__64")]
	private void mT__64()
	{
		EnterRule_T__64();
		EnterRule("T__64", 26);
		TraceIn("T__64", 26);
		try
		{
			int _type = T__64;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:32:7: ( 'então' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:32:9: 'então'
			{
			DebugLocation(32, 9);
			Match("então"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__64", 26);
			LeaveRule("T__64", 26);
			LeaveRule_T__64();
		}
	}
	// $ANTLR end "T__64"

	partial void EnterRule_T__65();
	partial void LeaveRule_T__65();

	// $ANTLR start "T__65"
	[GrammarRule("T__65")]
	private void mT__65()
	{
		EnterRule_T__65();
		EnterRule("T__65", 27);
		TraceIn("T__65", 27);
		try
		{
			int _type = T__65;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:33:7: ( 'fim' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:33:9: 'fim'
			{
			DebugLocation(33, 9);
			Match("fim"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__65", 27);
			LeaveRule("T__65", 27);
			LeaveRule_T__65();
		}
	}
	// $ANTLR end "T__65"

	partial void EnterRule_T__66();
	partial void LeaveRule_T__66();

	// $ANTLR start "T__66"
	[GrammarRule("T__66")]
	private void mT__66()
	{
		EnterRule_T__66();
		EnterRule("T__66", 28);
		TraceIn("T__66", 28);
		try
		{
			int _type = T__66;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:34:7: ( 'função' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:34:9: 'função'
			{
			DebugLocation(34, 9);
			Match("função"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__66", 28);
			LeaveRule("T__66", 28);
			LeaveRule_T__66();
		}
	}
	// $ANTLR end "T__66"

	partial void EnterRule_T__67();
	partial void LeaveRule_T__67();

	// $ANTLR start "T__67"
	[GrammarRule("T__67")]
	private void mT__67()
	{
		EnterRule_T__67();
		EnterRule("T__67", 29);
		TraceIn("T__67", 29);
		try
		{
			int _type = T__67;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:35:7: ( 'ou' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:35:9: 'ou'
			{
			DebugLocation(35, 9);
			Match("ou"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__67", 29);
			LeaveRule("T__67", 29);
			LeaveRule_T__67();
		}
	}
	// $ANTLR end "T__67"

	partial void EnterRule_T__68();
	partial void LeaveRule_T__68();

	// $ANTLR start "T__68"
	[GrammarRule("T__68")]
	private void mT__68()
	{
		EnterRule_T__68();
		EnterRule("T__68", 30);
		TraceIn("T__68", 30);
		try
		{
			int _type = T__68;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:36:7: ( 'para' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:36:9: 'para'
			{
			DebugLocation(36, 9);
			Match("para"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__68", 30);
			LeaveRule("T__68", 30);
			LeaveRule_T__68();
		}
	}
	// $ANTLR end "T__68"

	partial void EnterRule_T__69();
	partial void LeaveRule_T__69();

	// $ANTLR start "T__69"
	[GrammarRule("T__69")]
	private void mT__69()
	{
		EnterRule_T__69();
		EnterRule("T__69", 31);
		TraceIn("T__69", 31);
		try
		{
			int _type = T__69;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:37:7: ( 'repita' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:37:9: 'repita'
			{
			DebugLocation(37, 9);
			Match("repita"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__69", 31);
			LeaveRule("T__69", 31);
			LeaveRule_T__69();
		}
	}
	// $ANTLR end "T__69"

	partial void EnterRule_T__70();
	partial void LeaveRule_T__70();

	// $ANTLR start "T__70"
	[GrammarRule("T__70")]
	private void mT__70()
	{
		EnterRule_T__70();
		EnterRule("T__70", 32);
		TraceIn("T__70", 32);
		try
		{
			int _type = T__70;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:38:7: ( 'retorne' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:38:9: 'retorne'
			{
			DebugLocation(38, 9);
			Match("retorne"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__70", 32);
			LeaveRule("T__70", 32);
			LeaveRule_T__70();
		}
	}
	// $ANTLR end "T__70"

	partial void EnterRule_T__71();
	partial void LeaveRule_T__71();

	// $ANTLR start "T__71"
	[GrammarRule("T__71")]
	private void mT__71()
	{
		EnterRule_T__71();
		EnterRule("T__71", 33);
		TraceIn("T__71", 33);
		try
		{
			int _type = T__71;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:39:7: ( 'se' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:39:9: 'se'
			{
			DebugLocation(39, 9);
			Match("se"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__71", 33);
			LeaveRule("T__71", 33);
			LeaveRule_T__71();
		}
	}
	// $ANTLR end "T__71"

	partial void EnterRule_T__72();
	partial void LeaveRule_T__72();

	// $ANTLR start "T__72"
	[GrammarRule("T__72")]
	private void mT__72()
	{
		EnterRule_T__72();
		EnterRule("T__72", 34);
		TraceIn("T__72", 34);
		try
		{
			int _type = T__72;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:40:7: ( 'senão' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:40:9: 'senão'
			{
			DebugLocation(40, 9);
			Match("senão"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__72", 34);
			LeaveRule("T__72", 34);
			LeaveRule_T__72();
		}
	}
	// $ANTLR end "T__72"

	partial void EnterRule_T__73();
	partial void LeaveRule_T__73();

	// $ANTLR start "T__73"
	[GrammarRule("T__73")]
	private void mT__73()
	{
		EnterRule_T__73();
		EnterRule("T__73", 35);
		TraceIn("T__73", 35);
		try
		{
			int _type = T__73;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:41:7: ( 'variável' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:41:9: 'variável'
			{
			DebugLocation(41, 9);
			Match("variável"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__73", 35);
			LeaveRule("T__73", 35);
			LeaveRule_T__73();
		}
	}
	// $ANTLR end "T__73"

	partial void EnterRule_T__74();
	partial void LeaveRule_T__74();

	// $ANTLR start "T__74"
	[GrammarRule("T__74")]
	private void mT__74()
	{
		EnterRule_T__74();
		EnterRule("T__74", 36);
		TraceIn("T__74", 36);
		try
		{
			int _type = T__74;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:42:7: ( '{' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:42:9: '{'
			{
			DebugLocation(42, 9);
			Match('{'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__74", 36);
			LeaveRule("T__74", 36);
			LeaveRule_T__74();
		}
	}
	// $ANTLR end "T__74"

	partial void EnterRule_T__75();
	partial void LeaveRule_T__75();

	// $ANTLR start "T__75"
	[GrammarRule("T__75")]
	private void mT__75()
	{
		EnterRule_T__75();
		EnterRule("T__75", 37);
		TraceIn("T__75", 37);
		try
		{
			int _type = T__75;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:43:7: ( '}' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:43:9: '}'
			{
			DebugLocation(43, 9);
			Match('}'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__75", 37);
			LeaveRule("T__75", 37);
			LeaveRule_T__75();
		}
	}
	// $ANTLR end "T__75"

	partial void EnterRule_T();
	partial void LeaveRule_T();

	// $ANTLR start "T"
	[GrammarRule("T")]
	private void mT()
	{
		EnterRule_T();
		EnterRule("T", 38);
		TraceIn("T", 38);
		try
		{
			int _type = T;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:219:4: ( 'verdadeiro' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:219:7: 'verdadeiro'
			{
			DebugLocation(219, 7);
			Match("verdadeiro"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T", 38);
			LeaveRule("T", 38);
			LeaveRule_T();
		}
	}
	// $ANTLR end "T"

	partial void EnterRule_F();
	partial void LeaveRule_F();

	// $ANTLR start "F"
	[GrammarRule("F")]
	private void mF()
	{
		EnterRule_F();
		EnterRule("F", 39);
		TraceIn("F", 39);
		try
		{
			int _type = F;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:220:3: ( 'falso' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:220:5: 'falso'
			{
			DebugLocation(220, 5);
			Match("falso"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("F", 39);
			LeaveRule("F", 39);
			LeaveRule_F();
		}
	}
	// $ANTLR end "F"

	partial void EnterRule_ID();
	partial void LeaveRule_ID();

	// $ANTLR start "ID"
	[GrammarRule("ID")]
	private void mID()
	{
		EnterRule_ID();
		EnterRule("ID", 40);
		TraceIn("ID", 40);
		try
		{
			int _type = ID;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:221:4: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:221:6: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
			{
			DebugLocation(221, 6);
			if ((input.LA(1)>='A' && input.LA(1)<='Z')||input.LA(1)=='_'||(input.LA(1)>='a' && input.LA(1)<='z'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(221, 30);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:221:30: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
			try { DebugEnterSubRule(1);
			while (true)
			{
				int alt1=2;
				try { DebugEnterDecision(1, false);
				int LA1_0 = input.LA(1);

				if (((LA1_0>='0' && LA1_0<='9')||(LA1_0>='A' && LA1_0<='Z')||LA1_0=='_'||(LA1_0>='a' && LA1_0<='z')))
				{
					alt1 = 1;
				}


				} finally { DebugExitDecision(1); }
				switch ( alt1 )
				{
				case 1:
					DebugEnterAlt(1);
					// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:
					{
					DebugLocation(221, 30);
					input.Consume();


					}
					break;

				default:
					goto loop1;
				}
			}

			loop1:
				;

			} finally { DebugExitSubRule(1); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ID", 40);
			LeaveRule("ID", 40);
			LeaveRule_ID();
		}
	}
	// $ANTLR end "ID"

	partial void EnterRule_INT();
	partial void LeaveRule_INT();

	// $ANTLR start "INT"
	[GrammarRule("INT")]
	private void mINT()
	{
		EnterRule_INT();
		EnterRule("INT", 41);
		TraceIn("INT", 41);
		try
		{
			int _type = INT;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:223:5: ( ( '0' .. '9' )+ )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:223:7: ( '0' .. '9' )+
			{
			DebugLocation(223, 7);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:223:7: ( '0' .. '9' )+
			int cnt2=0;
			try { DebugEnterSubRule(2);
			while (true)
			{
				int alt2=2;
				try { DebugEnterDecision(2, false);
				int LA2_0 = input.LA(1);

				if (((LA2_0>='0' && LA2_0<='9')))
				{
					alt2 = 1;
				}


				} finally { DebugExitDecision(2); }
				switch (alt2)
				{
				case 1:
					DebugEnterAlt(1);
					// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:
					{
					DebugLocation(223, 7);
					input.Consume();


					}
					break;

				default:
					if (cnt2 >= 1)
						goto loop2;

					EarlyExitException eee2 = new EarlyExitException( 2, input );
					DebugRecognitionException(eee2);
					throw eee2;
				}
				cnt2++;
			}
			loop2:
				;

			} finally { DebugExitSubRule(2); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("INT", 41);
			LeaveRule("INT", 41);
			LeaveRule_INT();
		}
	}
	// $ANTLR end "INT"

	partial void EnterRule_FLOAT();
	partial void LeaveRule_FLOAT();

	// $ANTLR start "FLOAT"
	[GrammarRule("FLOAT")]
	private void mFLOAT()
	{
		EnterRule_FLOAT();
		EnterRule("FLOAT", 42);
		TraceIn("FLOAT", 42);
		try
		{
			int _type = FLOAT;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:225:7: ( INT '.' INT )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:225:8: INT '.' INT
			{
			DebugLocation(225, 8);
			mINT(); 
			DebugLocation(225, 12);
			Match('.'); 
			DebugLocation(225, 16);
			mINT(); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("FLOAT", 42);
			LeaveRule("FLOAT", 42);
			LeaveRule_FLOAT();
		}
	}
	// $ANTLR end "FLOAT"

	partial void EnterRule_NEWLINE();
	partial void LeaveRule_NEWLINE();

	// $ANTLR start "NEWLINE"
	[GrammarRule("NEWLINE")]
	private void mNEWLINE()
	{
		EnterRule_NEWLINE();
		EnterRule("NEWLINE", 43);
		TraceIn("NEWLINE", 43);
		try
		{
			int _type = NEWLINE;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:227:9: ( ( '\\r' )? '\\n' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:227:11: ( '\\r' )? '\\n'
			{
			DebugLocation(227, 11);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:227:11: ( '\\r' )?
			int alt3=2;
			try { DebugEnterSubRule(3);
			try { DebugEnterDecision(3, false);
			int LA3_0 = input.LA(1);

			if ((LA3_0=='\r'))
			{
				alt3 = 1;
			}
			} finally { DebugExitDecision(3); }
			switch (alt3)
			{
			case 1:
				DebugEnterAlt(1);
				// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:227:11: '\\r'
				{
				DebugLocation(227, 11);
				Match('\r'); 

				}
				break;

			}
			} finally { DebugExitSubRule(3); }

			DebugLocation(227, 16);
			Match('\n'); 
			DebugLocation(227, 22);
			 _channel = Hidden; 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NEWLINE", 43);
			LeaveRule("NEWLINE", 43);
			LeaveRule_NEWLINE();
		}
	}
	// $ANTLR end "NEWLINE"

	partial void EnterRule_WS();
	partial void LeaveRule_WS();

	// $ANTLR start "WS"
	[GrammarRule("WS")]
	private void mWS()
	{
		EnterRule_WS();
		EnterRule("WS", 44);
		TraceIn("WS", 44);
		try
		{
			int _type = WS;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:229:4: ( ( ' ' | '\\t' | '\\r' | '\\n' )+ )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:229:6: ( ' ' | '\\t' | '\\r' | '\\n' )+
			{
			DebugLocation(229, 6);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:229:6: ( ' ' | '\\t' | '\\r' | '\\n' )+
			int cnt4=0;
			try { DebugEnterSubRule(4);
			while (true)
			{
				int alt4=2;
				try { DebugEnterDecision(4, false);
				int LA4_0 = input.LA(1);

				if (((LA4_0>='\t' && LA4_0<='\n')||LA4_0=='\r'||LA4_0==' '))
				{
					alt4 = 1;
				}


				} finally { DebugExitDecision(4); }
				switch (alt4)
				{
				case 1:
					DebugEnterAlt(1);
					// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:
					{
					DebugLocation(229, 6);
					input.Consume();


					}
					break;

				default:
					if (cnt4 >= 1)
						goto loop4;

					EarlyExitException eee4 = new EarlyExitException( 4, input );
					DebugRecognitionException(eee4);
					throw eee4;
				}
				cnt4++;
			}
			loop4:
				;

			} finally { DebugExitSubRule(4); }

			DebugLocation(229, 36);
			 _channel = Hidden; 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WS", 44);
			LeaveRule("WS", 44);
			LeaveRule_WS();
		}
	}
	// $ANTLR end "WS"

	partial void EnterRule_STRING();
	partial void LeaveRule_STRING();

	// $ANTLR start "STRING"
	[GrammarRule("STRING")]
	private void mSTRING()
	{
		EnterRule_STRING();
		EnterRule("STRING", 45);
		TraceIn("STRING", 45);
		try
		{
			int _type = STRING;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:232:5: ( '\"' ( ESC_SEQ |~ ( '\\\\' | '\"' ) )* '\"' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:232:7: '\"' ( ESC_SEQ |~ ( '\\\\' | '\"' ) )* '\"'
			{
			DebugLocation(232, 7);
			Match('\"'); 
			DebugLocation(232, 11);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:232:11: ( ESC_SEQ |~ ( '\\\\' | '\"' ) )*
			try { DebugEnterSubRule(5);
			while (true)
			{
				int alt5=3;
				try { DebugEnterDecision(5, false);
				int LA5_0 = input.LA(1);

				if ((LA5_0=='\\'))
				{
					alt5 = 1;
				}
				else if (((LA5_0>='\u0000' && LA5_0<='!')||(LA5_0>='#' && LA5_0<='[')||(LA5_0>=']' && LA5_0<='\uFFFF')))
				{
					alt5 = 2;
				}


				} finally { DebugExitDecision(5); }
				switch ( alt5 )
				{
				case 1:
					DebugEnterAlt(1);
					// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:232:13: ESC_SEQ
					{
					DebugLocation(232, 13);
					mESC_SEQ(); 

					}
					break;
				case 2:
					DebugEnterAlt(2);
					// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:232:23: ~ ( '\\\\' | '\"' )
					{
					DebugLocation(232, 23);
					input.Consume();


					}
					break;

				default:
					goto loop5;
				}
			}

			loop5:
				;

			} finally { DebugExitSubRule(5); }

			DebugLocation(232, 38);
			Match('\"'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("STRING", 45);
			LeaveRule("STRING", 45);
			LeaveRule_STRING();
		}
	}
	// $ANTLR end "STRING"

	partial void EnterRule_CHAR();
	partial void LeaveRule_CHAR();

	// $ANTLR start "CHAR"
	[GrammarRule("CHAR")]
	private void mCHAR()
	{
		EnterRule_CHAR();
		EnterRule("CHAR", 46);
		TraceIn("CHAR", 46);
		try
		{
			int _type = CHAR;
			int _channel = DefaultTokenChannel;
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:235:5: ( '\\'' ( ESC_SEQ |~ ( '\\'' | '\\\\' ) ) '\\'' )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:235:7: '\\'' ( ESC_SEQ |~ ( '\\'' | '\\\\' ) ) '\\''
			{
			DebugLocation(235, 7);
			Match('\''); 
			DebugLocation(235, 12);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:235:12: ( ESC_SEQ |~ ( '\\'' | '\\\\' ) )
			int alt6=2;
			try { DebugEnterSubRule(6);
			try { DebugEnterDecision(6, false);
			int LA6_0 = input.LA(1);

			if ((LA6_0=='\\'))
			{
				alt6 = 1;
			}
			else if (((LA6_0>='\u0000' && LA6_0<='&')||(LA6_0>='(' && LA6_0<='[')||(LA6_0>=']' && LA6_0<='\uFFFF')))
			{
				alt6 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 6, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(6); }
			switch (alt6)
			{
			case 1:
				DebugEnterAlt(1);
				// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:235:14: ESC_SEQ
				{
				DebugLocation(235, 14);
				mESC_SEQ(); 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:235:24: ~ ( '\\'' | '\\\\' )
				{
				DebugLocation(235, 24);
				input.Consume();


				}
				break;

			}
			} finally { DebugExitSubRule(6); }

			DebugLocation(235, 39);
			Match('\''); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("CHAR", 46);
			LeaveRule("CHAR", 46);
			LeaveRule_CHAR();
		}
	}
	// $ANTLR end "CHAR"

	partial void EnterRule_EXPONENT();
	partial void LeaveRule_EXPONENT();

	// $ANTLR start "EXPONENT"
	[GrammarRule("EXPONENT")]
	private void mEXPONENT()
	{
		EnterRule_EXPONENT();
		EnterRule("EXPONENT", 47);
		TraceIn("EXPONENT", 47);
		try
		{
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:240:10: ( ( 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+ )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:240:12: ( 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+
			{
			DebugLocation(240, 12);
			if (input.LA(1)=='E'||input.LA(1)=='e')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(240, 22);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:240:22: ( '+' | '-' )?
			int alt7=2;
			try { DebugEnterSubRule(7);
			try { DebugEnterDecision(7, false);
			int LA7_0 = input.LA(1);

			if ((LA7_0=='+'||LA7_0=='-'))
			{
				alt7 = 1;
			}
			} finally { DebugExitDecision(7); }
			switch (alt7)
			{
			case 1:
				DebugEnterAlt(1);
				// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:
				{
				DebugLocation(240, 22);
				input.Consume();


				}
				break;

			}
			} finally { DebugExitSubRule(7); }

			DebugLocation(240, 33);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:240:33: ( '0' .. '9' )+
			int cnt8=0;
			try { DebugEnterSubRule(8);
			while (true)
			{
				int alt8=2;
				try { DebugEnterDecision(8, false);
				int LA8_0 = input.LA(1);

				if (((LA8_0>='0' && LA8_0<='9')))
				{
					alt8 = 1;
				}


				} finally { DebugExitDecision(8); }
				switch (alt8)
				{
				case 1:
					DebugEnterAlt(1);
					// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:
					{
					DebugLocation(240, 33);
					input.Consume();


					}
					break;

				default:
					if (cnt8 >= 1)
						goto loop8;

					EarlyExitException eee8 = new EarlyExitException( 8, input );
					DebugRecognitionException(eee8);
					throw eee8;
				}
				cnt8++;
			}
			loop8:
				;

			} finally { DebugExitSubRule(8); }


			}

		}
		finally
		{
			TraceOut("EXPONENT", 47);
			LeaveRule("EXPONENT", 47);
			LeaveRule_EXPONENT();
		}
	}
	// $ANTLR end "EXPONENT"

	partial void EnterRule_HEX_DIGIT();
	partial void LeaveRule_HEX_DIGIT();

	// $ANTLR start "HEX_DIGIT"
	[GrammarRule("HEX_DIGIT")]
	private void mHEX_DIGIT()
	{
		EnterRule_HEX_DIGIT();
		EnterRule("HEX_DIGIT", 48);
		TraceIn("HEX_DIGIT", 48);
		try
		{
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:243:11: ( ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' ) )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:
			{
			DebugLocation(243, 11);
			if ((input.LA(1)>='0' && input.LA(1)<='9')||(input.LA(1)>='A' && input.LA(1)<='F')||(input.LA(1)>='a' && input.LA(1)<='f'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("HEX_DIGIT", 48);
			LeaveRule("HEX_DIGIT", 48);
			LeaveRule_HEX_DIGIT();
		}
	}
	// $ANTLR end "HEX_DIGIT"

	partial void EnterRule_ESC_SEQ();
	partial void LeaveRule_ESC_SEQ();

	// $ANTLR start "ESC_SEQ"
	[GrammarRule("ESC_SEQ")]
	private void mESC_SEQ()
	{
		EnterRule_ESC_SEQ();
		EnterRule("ESC_SEQ", 49);
		TraceIn("ESC_SEQ", 49);
		try
		{
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:247:5: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' ) | UNICODE_ESC | OCTAL_ESC )
			int alt9=3;
			try { DebugEnterDecision(9, false);
			int LA9_0 = input.LA(1);

			if ((LA9_0=='\\'))
			{
				switch (input.LA(2))
				{
				case '\"':
				case '\'':
				case '\\':
				case 'b':
				case 'f':
				case 'n':
				case 'r':
				case 't':
					{
					alt9 = 1;
					}
					break;
				case 'u':
					{
					alt9 = 2;
					}
					break;
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
					{
					alt9 = 3;
					}
					break;
				default:
					{
						NoViableAltException nvae = new NoViableAltException("", 9, 1, input);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}

			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 9, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(9); }
			switch (alt9)
			{
			case 1:
				DebugEnterAlt(1);
				// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:247:7: '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' )
				{
				DebugLocation(247, 7);
				Match('\\'); 
				DebugLocation(247, 12);
				input.Consume();


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:248:7: UNICODE_ESC
				{
				DebugLocation(248, 7);
				mUNICODE_ESC(); 

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:249:7: OCTAL_ESC
				{
				DebugLocation(249, 7);
				mOCTAL_ESC(); 

				}
				break;

			}
		}
		finally
		{
			TraceOut("ESC_SEQ", 49);
			LeaveRule("ESC_SEQ", 49);
			LeaveRule_ESC_SEQ();
		}
	}
	// $ANTLR end "ESC_SEQ"

	partial void EnterRule_OCTAL_ESC();
	partial void LeaveRule_OCTAL_ESC();

	// $ANTLR start "OCTAL_ESC"
	[GrammarRule("OCTAL_ESC")]
	private void mOCTAL_ESC()
	{
		EnterRule_OCTAL_ESC();
		EnterRule("OCTAL_ESC", 50);
		TraceIn("OCTAL_ESC", 50);
		try
		{
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:254:5: ( '\\\\' ( '0' .. '3' ) ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) )
			int alt10=3;
			try { DebugEnterDecision(10, false);
			int LA10_0 = input.LA(1);

			if ((LA10_0=='\\'))
			{
				int LA10_1 = input.LA(2);

				if (((LA10_1>='0' && LA10_1<='3')))
				{
					int LA10_2 = input.LA(3);

					if (((LA10_2>='0' && LA10_2<='7')))
					{
						int LA10_4 = input.LA(4);

						if (((LA10_4>='0' && LA10_4<='7')))
						{
							alt10 = 1;
						}
						else
						{
							alt10 = 2;
						}
					}
					else
					{
						alt10 = 3;
					}
				}
				else if (((LA10_1>='4' && LA10_1<='7')))
				{
					int LA10_3 = input.LA(3);

					if (((LA10_3>='0' && LA10_3<='7')))
					{
						alt10 = 2;
					}
					else
					{
						alt10 = 3;
					}
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 10, 1, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 10, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(10); }
			switch (alt10)
			{
			case 1:
				DebugEnterAlt(1);
				// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:254:7: '\\\\' ( '0' .. '3' ) ( '0' .. '7' ) ( '0' .. '7' )
				{
				DebugLocation(254, 7);
				Match('\\'); 
				DebugLocation(254, 12);
				input.Consume();

				DebugLocation(254, 23);
				input.Consume();

				DebugLocation(254, 34);
				input.Consume();


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:255:7: '\\\\' ( '0' .. '7' ) ( '0' .. '7' )
				{
				DebugLocation(255, 7);
				Match('\\'); 
				DebugLocation(255, 12);
				input.Consume();

				DebugLocation(255, 23);
				input.Consume();


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:256:7: '\\\\' ( '0' .. '7' )
				{
				DebugLocation(256, 7);
				Match('\\'); 
				DebugLocation(256, 12);
				input.Consume();


				}
				break;

			}
		}
		finally
		{
			TraceOut("OCTAL_ESC", 50);
			LeaveRule("OCTAL_ESC", 50);
			LeaveRule_OCTAL_ESC();
		}
	}
	// $ANTLR end "OCTAL_ESC"

	partial void EnterRule_UNICODE_ESC();
	partial void LeaveRule_UNICODE_ESC();

	// $ANTLR start "UNICODE_ESC"
	[GrammarRule("UNICODE_ESC")]
	private void mUNICODE_ESC()
	{
		EnterRule_UNICODE_ESC();
		EnterRule("UNICODE_ESC", 51);
		TraceIn("UNICODE_ESC", 51);
		try
		{
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:261:5: ( '\\\\' 'u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT )
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:261:7: '\\\\' 'u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT
			{
			DebugLocation(261, 7);
			Match('\\'); 
			DebugLocation(261, 12);
			Match('u'); 
			DebugLocation(261, 16);
			mHEX_DIGIT(); 
			DebugLocation(261, 26);
			mHEX_DIGIT(); 
			DebugLocation(261, 36);
			mHEX_DIGIT(); 
			DebugLocation(261, 46);
			mHEX_DIGIT(); 

			}

		}
		finally
		{
			TraceOut("UNICODE_ESC", 51);
			LeaveRule("UNICODE_ESC", 51);
			LeaveRule_UNICODE_ESC();
		}
	}
	// $ANTLR end "UNICODE_ESC"

	public override void mTokens()
	{
		// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:8: ( T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | T__46 | T__47 | T__48 | T__49 | T__50 | T__51 | T__52 | T__53 | T__54 | T__55 | T__56 | T__57 | T__58 | T__59 | T__60 | T__61 | T__62 | T__63 | T__64 | T__65 | T__66 | T__67 | T__68 | T__69 | T__70 | T__71 | T__72 | T__73 | T__74 | T__75 | T | F | ID | INT | FLOAT | NEWLINE | WS | STRING | CHAR )
		int alt11=46;
		try { DebugEnterDecision(11, false);
		try
		{
			alt11 = dfa11.Predict(input);
		}
		catch (NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
			throw;
		}
		} finally { DebugExitDecision(11); }
		switch (alt11)
		{
		case 1:
			DebugEnterAlt(1);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:10: T__39
			{
			DebugLocation(1, 10);
			mT__39(); 

			}
			break;
		case 2:
			DebugEnterAlt(2);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:16: T__40
			{
			DebugLocation(1, 16);
			mT__40(); 

			}
			break;
		case 3:
			DebugEnterAlt(3);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:22: T__41
			{
			DebugLocation(1, 22);
			mT__41(); 

			}
			break;
		case 4:
			DebugEnterAlt(4);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:28: T__42
			{
			DebugLocation(1, 28);
			mT__42(); 

			}
			break;
		case 5:
			DebugEnterAlt(5);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:34: T__43
			{
			DebugLocation(1, 34);
			mT__43(); 

			}
			break;
		case 6:
			DebugEnterAlt(6);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:40: T__44
			{
			DebugLocation(1, 40);
			mT__44(); 

			}
			break;
		case 7:
			DebugEnterAlt(7);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:46: T__45
			{
			DebugLocation(1, 46);
			mT__45(); 

			}
			break;
		case 8:
			DebugEnterAlt(8);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:52: T__46
			{
			DebugLocation(1, 52);
			mT__46(); 

			}
			break;
		case 9:
			DebugEnterAlt(9);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:58: T__47
			{
			DebugLocation(1, 58);
			mT__47(); 

			}
			break;
		case 10:
			DebugEnterAlt(10);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:64: T__48
			{
			DebugLocation(1, 64);
			mT__48(); 

			}
			break;
		case 11:
			DebugEnterAlt(11);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:70: T__49
			{
			DebugLocation(1, 70);
			mT__49(); 

			}
			break;
		case 12:
			DebugEnterAlt(12);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:76: T__50
			{
			DebugLocation(1, 76);
			mT__50(); 

			}
			break;
		case 13:
			DebugEnterAlt(13);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:82: T__51
			{
			DebugLocation(1, 82);
			mT__51(); 

			}
			break;
		case 14:
			DebugEnterAlt(14);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:88: T__52
			{
			DebugLocation(1, 88);
			mT__52(); 

			}
			break;
		case 15:
			DebugEnterAlt(15);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:94: T__53
			{
			DebugLocation(1, 94);
			mT__53(); 

			}
			break;
		case 16:
			DebugEnterAlt(16);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:100: T__54
			{
			DebugLocation(1, 100);
			mT__54(); 

			}
			break;
		case 17:
			DebugEnterAlt(17);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:106: T__55
			{
			DebugLocation(1, 106);
			mT__55(); 

			}
			break;
		case 18:
			DebugEnterAlt(18);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:112: T__56
			{
			DebugLocation(1, 112);
			mT__56(); 

			}
			break;
		case 19:
			DebugEnterAlt(19);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:118: T__57
			{
			DebugLocation(1, 118);
			mT__57(); 

			}
			break;
		case 20:
			DebugEnterAlt(20);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:124: T__58
			{
			DebugLocation(1, 124);
			mT__58(); 

			}
			break;
		case 21:
			DebugEnterAlt(21);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:130: T__59
			{
			DebugLocation(1, 130);
			mT__59(); 

			}
			break;
		case 22:
			DebugEnterAlt(22);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:136: T__60
			{
			DebugLocation(1, 136);
			mT__60(); 

			}
			break;
		case 23:
			DebugEnterAlt(23);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:142: T__61
			{
			DebugLocation(1, 142);
			mT__61(); 

			}
			break;
		case 24:
			DebugEnterAlt(24);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:148: T__62
			{
			DebugLocation(1, 148);
			mT__62(); 

			}
			break;
		case 25:
			DebugEnterAlt(25);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:154: T__63
			{
			DebugLocation(1, 154);
			mT__63(); 

			}
			break;
		case 26:
			DebugEnterAlt(26);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:160: T__64
			{
			DebugLocation(1, 160);
			mT__64(); 

			}
			break;
		case 27:
			DebugEnterAlt(27);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:166: T__65
			{
			DebugLocation(1, 166);
			mT__65(); 

			}
			break;
		case 28:
			DebugEnterAlt(28);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:172: T__66
			{
			DebugLocation(1, 172);
			mT__66(); 

			}
			break;
		case 29:
			DebugEnterAlt(29);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:178: T__67
			{
			DebugLocation(1, 178);
			mT__67(); 

			}
			break;
		case 30:
			DebugEnterAlt(30);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:184: T__68
			{
			DebugLocation(1, 184);
			mT__68(); 

			}
			break;
		case 31:
			DebugEnterAlt(31);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:190: T__69
			{
			DebugLocation(1, 190);
			mT__69(); 

			}
			break;
		case 32:
			DebugEnterAlt(32);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:196: T__70
			{
			DebugLocation(1, 196);
			mT__70(); 

			}
			break;
		case 33:
			DebugEnterAlt(33);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:202: T__71
			{
			DebugLocation(1, 202);
			mT__71(); 

			}
			break;
		case 34:
			DebugEnterAlt(34);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:208: T__72
			{
			DebugLocation(1, 208);
			mT__72(); 

			}
			break;
		case 35:
			DebugEnterAlt(35);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:214: T__73
			{
			DebugLocation(1, 214);
			mT__73(); 

			}
			break;
		case 36:
			DebugEnterAlt(36);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:220: T__74
			{
			DebugLocation(1, 220);
			mT__74(); 

			}
			break;
		case 37:
			DebugEnterAlt(37);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:226: T__75
			{
			DebugLocation(1, 226);
			mT__75(); 

			}
			break;
		case 38:
			DebugEnterAlt(38);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:232: T
			{
			DebugLocation(1, 232);
			mT(); 

			}
			break;
		case 39:
			DebugEnterAlt(39);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:234: F
			{
			DebugLocation(1, 234);
			mF(); 

			}
			break;
		case 40:
			DebugEnterAlt(40);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:236: ID
			{
			DebugLocation(1, 236);
			mID(); 

			}
			break;
		case 41:
			DebugEnterAlt(41);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:239: INT
			{
			DebugLocation(1, 239);
			mINT(); 

			}
			break;
		case 42:
			DebugEnterAlt(42);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:243: FLOAT
			{
			DebugLocation(1, 243);
			mFLOAT(); 

			}
			break;
		case 43:
			DebugEnterAlt(43);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:249: NEWLINE
			{
			DebugLocation(1, 249);
			mNEWLINE(); 

			}
			break;
		case 44:
			DebugEnterAlt(44);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:257: WS
			{
			DebugLocation(1, 257);
			mWS(); 

			}
			break;
		case 45:
			DebugEnterAlt(45);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:260: STRING
			{
			DebugLocation(1, 260);
			mSTRING(); 

			}
			break;
		case 46:
			DebugEnterAlt(46);
			// E:\\Dev\\Git\\NPortugol\\src\\grammar\\NPortugol.g:1:267: CHAR
			{
			DebugLocation(1, 267);
			mCHAR(); 

			}
			break;

		}

	}


	#region DFA
	DFA11 dfa11;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa11 = new DFA11(this);
	}

	private class DFA11 : DFA
	{
		private const string DFA11_eotS =
			"\xA\xFFFF\x1\x25\x2\xFFFF\x1\x27\x1\x29\x1\x2B\x2\xFFFF\x2\x1D\x1\x2F"+
			"\x6\x1D\x3\xFFFF\x1\x39\x1\x21\x1\x3B\xB\xFFFF\x3\x1D\x1\xFFFF\x3\x1D"+
			"\x1\x43\x2\x1D\x1\x48\x2\x1D\x4\xFFFF\x3\x1D\x1\x4E\x2\x1D\x1\xFFFF\x4"+
			"\x1D\x1\xFFFF\x4\x1D\x3\xFFFF\x1\x1D\x1\x5A\x2\x1D\x1\xFFFF\x4\x1D\x1"+
			"\x61\x1\xFFFF\x2\x1D\x1\xFFFF\x3\x1D\x1\xFFFF\x1\x67\x4\x1D\x1\xFFFF"+
			"\x1\x6C\x2\x1D\x1\x6F\x1\xFFFF\x2\x1D\x1\xFFFF\x2\x1D\x1\x74\x1\x75\x2"+
			"\xFFFF";
		private const string DFA11_eofS =
			"\x76\xFFFF";
		private const string DFA11_minS =
			"\x1\x9\x9\xFFFF\x1\x2E\x2\xFFFF\x3\x3D\x2\xFFFF\x1\x74\x1\x65\x1\x30"+
			"\x1\x61\x1\x75\x1\x61\x2\x65\x1\x61\x3\xFFFF\x1\x2E\x1\xA\x1\x9\xB\xFFFF"+
			"\x1\xE9\x1\x63\x1\x71\x1\xFFFF\x1\x6D\x1\x6E\x1\x6C\x1\x30\x1\x72\x1"+
			"\x70\x1\x30\x2\x72\x4\xFFFF\x1\x72\x1\x75\x1\xE3\x1\x30\x1\xE7\x1\x73"+
			"\x1\xFFFF\x1\x61\x1\x69\x1\x6F\x1\xE3\x1\xFFFF\x1\x69\x1\x64\x1\x65\x1"+
			"\x61\x3\xFFFF\x1\x6F\x1\x30\x1\x74\x1\x72\x1\xFFFF\x1\xE1\x1\x61\x1\x73"+
			"\x1\x6E\x1\x30\x1\xFFFF\x1\x61\x1\x6E\x1\xFFFF\x1\x64\x1\x63\x1\x74\x1"+
			"\xFFFF\x1\x30\x3\x65\x1\x6F\x1\xFFFF\x1\x30\x1\x69\x1\x6E\x1\x30\x1\xFFFF"+
			"\x1\x72\x1\x74\x1\xFFFF\x1\x6F\x1\x65\x2\x30\x2\xFFFF";
		private const string DFA11_maxS =
			"\x1\x7D\x9\xFFFF\x1\x2E\x2\xFFFF\x3\x3D\x2\xFFFF\x1\x74\x1\x65\x1\x7A"+
			"\x2\x75\x1\x61\x3\x65\x3\xFFFF\x1\x39\x1\xA\x1\x20\xB\xFFFF\x1\xE9\x1"+
			"\x63\x1\x74\x1\xFFFF\x1\x6D\x1\x6E\x1\x6C\x1\x7A\x1\x72\x1\x74\x1\x7A"+
			"\x2\x72\x4\xFFFF\x1\x72\x1\x75\x1\xE3\x1\x7A\x1\xE7\x1\x73\x1\xFFFF\x1"+
			"\x61\x1\x69\x1\x6F\x1\xE3\x1\xFFFF\x1\x69\x1\x64\x1\x65\x1\x61\x3\xFFFF"+
			"\x1\x6F\x1\x7A\x1\x74\x1\x72\x1\xFFFF\x1\xE1\x1\x61\x1\x73\x1\x6E\x1"+
			"\x7A\x1\xFFFF\x1\x61\x1\x6E\x1\xFFFF\x1\x64\x1\x63\x1\x74\x1\xFFFF\x1"+
			"\x7A\x3\x65\x1\x6F\x1\xFFFF\x1\x7A\x1\x69\x1\x6E\x1\x7A\x1\xFFFF\x1\x72"+
			"\x1\x74\x1\xFFFF\x1\x6F\x1\x65\x2\x7A\x2\xFFFF";
		private const string DFA11_acceptS =
			"\x1\xFFFF\x1\x1\x1\x2\x1\x3\x1\x4\x1\x5\x1\x6\x1\x7\x1\x8\x1\x9\x1\xFFFF"+
			"\x1\xC\x1\xD\x3\xFFFF\x1\x14\x1\x15\x9\xFFFF\x1\x24\x1\x25\x1\x28\x3"+
			"\xFFFF\x1\x2C\x1\x2D\x1\x2E\x1\xB\x1\xA\x1\xF\x1\xE\x1\x11\x1\x10\x1"+
			"\x13\x1\x12\x3\xFFFF\x1\x18\x9\xFFFF\x1\x29\x1\x2A\x1\x2B\x1\x16\x6\xFFFF"+
			"\x1\x1D\x4\xFFFF\x1\x21\x4\xFFFF\x1\x1A\x1\x1B\x1\x1C\x4\xFFFF\x1\x22"+
			"\x5\xFFFF\x1\x1E\x2\xFFFF\x1\x23\x3\xFFFF\x1\x27\x5\xFFFF\x1\x1F\x4\xFFFF"+
			"\x1\x20\x2\xFFFF\x1\x19\x4\xFFFF\x1\x26\x1\x17";
		private const string DFA11_specialS =
			"\x76\xFFFF}>";
		private static readonly string[] DFA11_transitionS =
			{
				"\x1\x21\x1\x20\x2\xFFFF\x1\x1F\x12\xFFFF\x1\x21\x1\x1\x1\x22\x1\x2\x1"+
				"\xFFFF\x1\x3\x1\xFFFF\x1\x23\x1\x4\x1\x5\x1\x6\x1\x7\x1\x8\x1\x9\x1"+
				"\xA\x1\xB\xA\x1E\x1\xFFFF\x1\xC\x1\xD\x1\xE\x1\xF\x2\xFFFF\x1A\x1D\x1"+
				"\x10\x1\xFFFF\x1\x11\x1\xFFFF\x1\x1D\x1\xFFFF\x1\x12\x2\x1D\x1\x13\x1"+
				"\x14\x1\x15\x8\x1D\x1\x16\x1\x17\x1\x1D\x1\x18\x1\x19\x2\x1D\x1\x1A"+
				"\x4\x1D\x1\x1B\x1\xFFFF\x1\x1C",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\x24",
				"",
				"",
				"\x1\x26",
				"\x1\x28",
				"\x1\x2A",
				"",
				"",
				"\x1\x2C",
				"\x1\x2D",
				"\xA\x1D\x7\xFFFF\x1A\x1D\x4\xFFFF\x1\x1D\x1\xFFFF\xD\x1D\x1\x2E\xC"+
				"\x1D",
				"\x1\x32\x7\xFFFF\x1\x30\xB\xFFFF\x1\x31",
				"\x1\x33",
				"\x1\x34",
				"\x1\x35",
				"\x1\x36",
				"\x1\x37\x3\xFFFF\x1\x38",
				"",
				"",
				"",
				"\x1\x3A\x1\xFFFF\xA\x1E",
				"\x1\x20",
				"\x2\x21\x2\xFFFF\x1\x21\x12\xFFFF\x1\x21",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\x3C",
				"\x1\x3D",
				"\x1\x3E\x2\xFFFF\x1\x3F",
				"",
				"\x1\x40",
				"\x1\x41",
				"\x1\x42",
				"\xA\x1D\x7\xFFFF\x1A\x1D\x4\xFFFF\x1\x1D\x1\xFFFF\x1A\x1D",
				"\x1\x44",
				"\x1\x45\x3\xFFFF\x1\x46",
				"\xA\x1D\x7\xFFFF\x1A\x1D\x4\xFFFF\x1\x1D\x1\xFFFF\xD\x1D\x1\x47\xC"+
				"\x1D",
				"\x1\x49",
				"\x1\x4A",
				"",
				"",
				"",
				"",
				"\x1\x4B",
				"\x1\x4C",
				"\x1\x4D",
				"\xA\x1D\x7\xFFFF\x1A\x1D\x4\xFFFF\x1\x1D\x1\xFFFF\x1A\x1D",
				"\x1\x4F",
				"\x1\x50",
				"",
				"\x1\x51",
				"\x1\x52",
				"\x1\x53",
				"\x1\x54",
				"",
				"\x1\x55",
				"\x1\x56",
				"\x1\x57",
				"\x1\x58",
				"",
				"",
				"",
				"\x1\x59",
				"\xA\x1D\x7\xFFFF\x1A\x1D\x4\xFFFF\x1\x1D\x1\xFFFF\x1A\x1D",
				"\x1\x5B",
				"\x1\x5C",
				"",
				"\x1\x5D",
				"\x1\x5E",
				"\x1\x5F",
				"\x1\x60",
				"\xA\x1D\x7\xFFFF\x1A\x1D\x4\xFFFF\x1\x1D\x1\xFFFF\x1A\x1D",
				"",
				"\x1\x62",
				"\x1\x63",
				"",
				"\x1\x64",
				"\x1\x65",
				"\x1\x66",
				"",
				"\xA\x1D\x7\xFFFF\x1A\x1D\x4\xFFFF\x1\x1D\x1\xFFFF\x1A\x1D",
				"\x1\x68",
				"\x1\x69",
				"\x1\x6A",
				"\x1\x6B",
				"",
				"\xA\x1D\x7\xFFFF\x1A\x1D\x4\xFFFF\x1\x1D\x1\xFFFF\x1A\x1D",
				"\x1\x6D",
				"\x1\x6E",
				"\xA\x1D\x7\xFFFF\x1A\x1D\x4\xFFFF\x1\x1D\x1\xFFFF\x1A\x1D",
				"",
				"\x1\x70",
				"\x1\x71",
				"",
				"\x1\x72",
				"\x1\x73",
				"\xA\x1D\x7\xFFFF\x1A\x1D\x4\xFFFF\x1\x1D\x1\xFFFF\x1A\x1D",
				"\xA\x1D\x7\xFFFF\x1A\x1D\x4\xFFFF\x1\x1D\x1\xFFFF\x1A\x1D",
				"",
				""
			};

		private static readonly short[] DFA11_eot = DFA.UnpackEncodedString(DFA11_eotS);
		private static readonly short[] DFA11_eof = DFA.UnpackEncodedString(DFA11_eofS);
		private static readonly char[] DFA11_min = DFA.UnpackEncodedStringToUnsignedChars(DFA11_minS);
		private static readonly char[] DFA11_max = DFA.UnpackEncodedStringToUnsignedChars(DFA11_maxS);
		private static readonly short[] DFA11_accept = DFA.UnpackEncodedString(DFA11_acceptS);
		private static readonly short[] DFA11_special = DFA.UnpackEncodedString(DFA11_specialS);
		private static readonly short[][] DFA11_transition;

		static DFA11()
		{
			int numStates = DFA11_transitionS.Length;
			DFA11_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA11_transition[i] = DFA.UnpackEncodedString(DFA11_transitionS[i]);
			}
		}

		public DFA11( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 11;
			this.eot = DFA11_eot;
			this.eof = DFA11_eof;
			this.min = DFA11_min;
			this.max = DFA11_max;
			this.accept = DFA11_accept;
			this.special = DFA11_special;
			this.transition = DFA11_transition;
		}

		public override string Description { get { return "1:1: Tokens : ( T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | T__46 | T__47 | T__48 | T__49 | T__50 | T__51 | T__52 | T__53 | T__54 | T__55 | T__56 | T__57 | T__58 | T__59 | T__60 | T__61 | T__62 | T__63 | T__64 | T__65 | T__66 | T__67 | T__68 | T__69 | T__70 | T__71 | T__72 | T__73 | T__74 | T__75 | T | F | ID | INT | FLOAT | NEWLINE | WS | STRING | CHAR );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

 
	#endregion

}
